### ISSUE TITLE
bug(profile): Profile and Banner picture will be missing when updated

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink-UI_Kit#1680]
**Issue:**
If you update either your profile or banner picture, it will show up as grey to all your friends 

**OS:**
All

**Screenshot:**
<img width="963" alt="Screenshot 2024-01-04 at 2 27 42 PM" src="https://github.com/Satellite-im/Uplink/assets/93608357/2f4bfacc-3846-42dd-b331-e4e5ef1de89a">

![image](https://github.com/Satellite-im/Uplink/assets/93608357/1a716ee5-faf7-42e7-ae92-e632790787dd)

**Comment by dariusc93** [comment]
Looking into this, the image that is transferred and the base64 produced is continuing to be valid.

**Comment by dariusc93** [comment]
Looking more into this, it is because when using the shuttle discovery, the identity is pushed out from that node when there is an update to those connected, however images are excluded from that push and since there isnt any update or a difference in the identity on the second push, it does not attempt to fetch any images. Will be doing an update soon.
