### ISSUE TITLE
task(chats): load the conversations on initialization and not do based on what is there in the state

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Uplink-UI_Kit#1936]
task(chats): load the conversations on initialization and not do based on what is there in the state

**Comment by dariusc93** [comment]
To clarify, uplink relies on the state to list the conversation(s), however if the state.json is deleted or corrupted (or if the account is being recovered in #1935), uplink would not show the conversations in the side bar. While it is possible to load up direct messages by clicking on the chat button with friends, it would not be possible to load group conversations from warp since uplink does not provide any means for that. 

A solution would be :
1. To exclude the conversation metadata from `state.json` and load the conversation into the state in memory. 
2. Initialize the conversation in the state if there been any update between what is in warp compared to the data in state.json
